# Defines a default set of lint rules enforced for projects at Google. For
# details and rationale, see
# https://github.com/dart-lang/pedantic#enabled-lints.

include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - src/generated/**
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
linter:
  rules:
    - camel_case_types

