name: eventstore_client
version: 0.0.2
homepage: https://github.com/DISCOOS/eventstore-client-dart
description: A community developed gRPC client library for EventStoreDB. EventStoreDB is an open-source, functional database with Complex Event Processing capabilities.
repository: https://github.com/DISCOOS/eventstore-client-dart
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  uuid: ^3.0.4
  meta: ^1.7.0
  path: ^1.8.0
  grpc: ^3.0.2
  tuple: ^2.0.0
  async: ^2.8.2
  fixnum: ^1.0.0
  logging: ^1.0.1
  protobuf: ^2.0.0
  collection: ^1.15.0
  universal_io: ^2.0.4
dev_dependencies: 
  pedantic: ^1.10.0
  test: ^1.17.11
  mockito: ^5.0.14
  docker_process: ^1.3.0
