name: eventstore_client_test
version: 0.2.1
homepage: https://github.com/DISCOOS/eventstore-client-dart
description: A testing library for applications using EventStore Client with a local EventStoreDB instance.
repository: https://github.com/DISCOOS/eventstore-client-dart
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  args: ^2.3.0
  file: ^6.1.2
  path: ^1.8.0
  shell: ^2.0.0
  logging: ^1.0.2
  universal_io: ^2.0.4
  eventstore_client: ^0.2.1
dev_dependencies: 
  lints: ^1.0.0
  test: ^1.16.0
executables: 
  esdbtcli: cli
