# Defines a default set of lint rules enforced for projects at Google. For
# details and rationale, see
# https://github.com/dart-lang/pedantic#enabled-lints.

include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/src/generated/**
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    constant_identifier_names: ignore
    non_constant_identifier_names: ignore
    invalid_use_of_visible_for_overriding_member: ignore
