name: eventstore_client
version: 0.4.0
homepage: https://github.com/DISCOOS/eventstore-client-dart
description: A community developed gRPC client library for EventStoreDB. EventStoreDB is an open-source, functional database with Complex Event Processing capabilities.
repository: https://github.com/DISCOOS/eventstore-client-dart
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  uuid: ^3.0.4
  meta: ^1.7.0
  path: ^1.8.0
  grpc: ^3.0.2
  tuple: ^2.0.0
  async: ^2.8.1
  fixnum: ^1.0.0
  logging: ^1.0.1
  protobuf: ^2.0.0
  pub_semver: ^2.0.0
  collection: ^1.15.0
  universal_io: ^2.0.4
dev_dependencies: 
  lints: ^2.0.0
  test: ^1.16.0
  mockito: ^5.0.15
  eventstore_client_test: 
    path: ../eventstore_client_test
false_secrets: 
  - /test/certs/*
