# Created with package:mono_repo v6.3.0
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.3.0
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_and_format; PKGS: packages/eventstore_client, packages/eventstore_client_test; `dart analyze --fatal-infos .`, `dart format --output=none --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/eventstore_client-packages/eventstore_client_test;commands:analyze-format"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/eventstore_client-packages/eventstore_client_test
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: packages_eventstore_client_pub_upgrade
        name: packages/eventstore_client; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/eventstore_client
        run: dart pub upgrade
      - name: "packages/eventstore_client; dart analyze --fatal-infos ."
        if: "always() && steps.packages_eventstore_client_pub_upgrade.conclusion == 'success'"
        working-directory: packages/eventstore_client
        run: dart analyze --fatal-infos .
      - name: "packages/eventstore_client; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_eventstore_client_pub_upgrade.conclusion == 'success'"
        working-directory: packages/eventstore_client
        run: "dart format --output=none --set-exit-if-changed ."
      - id: packages_eventstore_client_test_pub_upgrade
        name: packages/eventstore_client_test; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/eventstore_client_test
        run: dart pub upgrade
      - name: "packages/eventstore_client_test; dart analyze --fatal-infos ."
        if: "always() && steps.packages_eventstore_client_test_pub_upgrade.conclusion == 'success'"
        working-directory: packages/eventstore_client_test
        run: dart analyze --fatal-infos .
      - name: "packages/eventstore_client_test; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_eventstore_client_test_pub_upgrade.conclusion == 'success'"
        working-directory: packages/eventstore_client_test
        run: "dart format --output=none --set-exit-if-changed ."
    needs:
      - job_001
  job_003:
    name: "Test & Publish coverage"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:packages/eventuous;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:packages/eventuous
            os:ubuntu-latest;pub-cache-hosted;dart:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.3.4
      - name: "packages/eventstore_client; dart pub upgrade && pub global activate coverage"
        working-directory: packages/eventstore_client
        run: "dart pub upgrade && pub global activate coverage"
      - name: packages/eventstore_client; Run tests with coverage
        working-directory: packages/eventstore_client
        run: "dart test -j 1 --reporter=expanded --coverage=\"coverage\""
      - name: packages/eventstore_client; Collect test coverage
        working-directory: packages/eventstore_client
        run: "format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.packages --report-on=lib"
      - name: Publish test coverage
        uses: codecov/codecov-action@v1.0.2
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
    needs:
      - job_001
      - job_002
